USE MASTER
GO

IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME='bd_ventas')
DROP DATABASE bd_ventas
GO
CREATE DATABASE bd_ventas
GO
USE bd_ventas
GO

-- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	TABLA AUTOMOVIL
---=====================================================================================
CREATE TABLE AUTOMOVIL
(
	ID_AUTOMOVIL	VARCHAR(9) NOT NULL,
	ID_MARCA		VARCHAR(9) NOT NULL,
	MODELO			VARCHAR(9) NOT NULL,
	COLOR			VARCHAR(32) NOT NULL,
	PRECIO			DECIMAL(15,2) NOT NULL,
	STOCK			INT NOT NULL,
	ESTADO			CHAR(1) NULL,
	FECHA_REGISTRO	VARCHAR(8) NULL,

	CONSTRAINT PK_AUTOMOVIL PRIMARY KEY CLUSTERED (ID_AUTOMOVIL ASC) 
    ON [PRIMARY] 
) 
GO

-- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	TABLA MARCAS
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='MARCA' AND TYPE='U')
DROP TABLE MARCA
GO

CREATE TABLE MARCA
(
	ID_MARCA		VARCHAR(9) NOT NULL,
	NOMBRE			VARCHAR(30) NOT NULL,
	NACIONALIDAD	VARCHAR(9) NULL,
	ESTADO			CHAR(1) NULL,
	FECHA_REGISTRO	DATETIME NULL,
	

	CONSTRAINT PK_MARCA PRIMARY KEY CLUSTERED (ID_MARCA ASC) 
    ON [PRIMARY] 
)
GO 

ALTER TABLE AUTOMOVIL 
	WITH CHECK 
	ADD CONSTRAINT FK_AUTOMOVIL_MARCA 
	FOREIGN KEY (ID_MARCA)
	REFERENCES MARCA (ID_MARCA)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
GO


-- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LOS AUTOMOVILES
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_AUTOMOVIL_CONSULTA' AND TYPE='P')
DROP PROC USP_AUTO_CONSULTA
GO

CREATE PROCEDURE USP_AUTOMOVIL_CONSULTA AS

SELECT	ID_AUTOMOVIL,
		ID_MARCA,
		MODELO,
		COLOR,
		PRECIO,
		STOCK,
		ESTADO
FROM AUTOMOVIL
WHERE ESTADO = 'A'
GO

--EXEC USP_AUTOMOVIL_CONSULTA
--GO

-- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA GENERAR CODIGO DE AUTOMOVIL
-- =====================================================================================
---------------------------- GENERAR CODIGO DE AUTOMOVIL ------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_GENERARCODIGOAUTOMOVIL' AND TYPE='P')
DROP PROC USP_GENERARCODIGOAUTOMOVIL
GO
CREATE proc USP_GENERARCODIGOAUTOMOVIL
AS
DECLARE @CODIGO CHAR(9)
SET @CODIGO=(SELECT MAX(ID_AUTOMOVIL) AS CODIGO FROM AUTOMOVIL)
SET @CODIGO='AUT'+RIGHT('00000'+LTRIM(RIGHT(ISNULL(@CODIGO,'00000'),6)+1),6)
SELECT @CODIGO AS CODIGO
GO

--EXEC USP_GENERARCODIGOAUTOMOVIL
--GO

-- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA GENERAR CODIGO DE MARCA
-- =====================================================================================
---------------------------- GENERAR CODIGO DE MARCA ------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_GENERARCODIGOMARCA' AND TYPE='P')
DROP PROC USP_GENERARCODIGOMARCA
GO
CREATE proc USP_GENERARCODIGOMARCA
AS
DECLARE @CODIGO CHAR(9)
SET @CODIGO=(SELECT MAX(ID_MARCA) AS CODIGO FROM MARCA)
SET @CODIGO='MAR'+RIGHT('00000'+LTRIM(RIGHT(ISNULL(@CODIGO,'00000'),6)+1),6)
SELECT @CODIGO AS CODIGO
GO

--EXEC USP_GENERARCODIGOMARCA
--GO

-- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LOS AUTOMOVILES
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_MARCA_CONSULTA_LISTA' AND TYPE='P')
DROP PROC USP_MARCA_CONSULTA_LISTA
GO

CREATE PROCEDURE USP_MARCA_CONSULTA_LISTA 
AS
SELECT	ID_MARCA,
		NOMBRE
FROM MARCA
WHERE ESTADO = 'A'
GO

EXEC USP_MARCA_CONSULTA_LISTA
GO

-- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA INSERTAR REGISTROS EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_INSERTAR_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_INSERTAR_AUTOMOVIL
GO

CREATE PROCEDURE USP_INSERTAR_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9),
	@ID_MARCA		AS VARCHAR(9),
	@MODELO			AS VARCHAR(9),
	@COLOR			AS VARCHAR(32),
	@PRECIO			AS DECIMAL(15,2),
	@STOCK			AS INT,
	@ESTADO			AS CHAR(1),
	@FECHA_REGISTRO AS VARCHAR(8)
AS
BEGIN
INSERT INTO AUTOMOVIL
	(
	ID_AUTOMOVIL,
	ID_MARCA,
	MODELO,
	COLOR,
	PRECIO,
	STOCK,
	ESTADO,
	FECHA_REGISTRO
	) 
	VALUES	
	(	
	@ID_AUTOMOVIL,
	@ID_MARCA,
	@MODELO,
	@COLOR,
	@PRECIO,
	@STOCK,
	@ESTADO,
	@FECHA_REGISTRO
	)
END
GO


-- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA ACTUALIZAR REGISTROS EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_UPDATE_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_UPDATE_AUTOMOVIL
GO

CREATE PROCEDURE USP_UPDATE_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9),
	@ID_MARCA		AS VARCHAR(9),
	@MODELO			AS VARCHAR(9),
	@COLOR			AS VARCHAR(32),
	@PRECIO			AS DECIMAL(15,2),
	@STOCK			AS INT
AS
UPDATE AUTOMOVIL
   SET	ID_MARCA = @ID_MARCA,
		MODELO = @MODELO,
		COLOR = @COLOR,
		PRECIO = @PRECIO,
		STOCK = @STOCK
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL
GO


-- =================================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA ELIMINAR UN REGISTROS EN lA TABLA AUTOMOVIL - ESTADO INACTIVO
-- =================================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_DELETE_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_DELETE_AUTOMOVIL
GO

CREATE PROCEDURE USP_DELETE_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9)
AS
UPDATE AUTOMOVIL
   SET	ESTADO = 'I'
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL
GO

--EXEC USP_DELETE_AUTOMOVIL 'AUT000001'
--GO


 -- =====================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA BUSCAR UN REGISTRO EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_BUSCAR_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_BUSCAR_AUTOMOVIL
GO

CREATE PROCEDURE USP_BUSCAR_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9)
AS
SELECT	ID_AUTOMOVIL,
		ID_MARCA,
		MODELO,
		COLOR,
		PRECIO,
		STOCK,
		ESTADO,
		FECHA_REGISTRO
FROM AUTOMOVIL
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL AND ESTADO = 'A'
GO

-- =========================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA MOSTRAR LA CANTIDAD DE REGISTROS EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_TOTAL_REGISTROS_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_TOTAL_REGISTROS_AUTOMOVIL
GO

CREATE PROCEDURE USP_TOTAL_REGISTROS_AUTOMOVIL 
AS
SELECT COUNT(*) AS CANTREG
FROM AUTOMOVIL
WHERE ESTADO = 'A'
GO

--EXEC USP_TOTAL_REGISTROS_AUTOMOVIL
--GO

-- =========================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LA PAGINACIÓN EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_PAGINACION_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_PAGINACION_AUTOMOVIL
GO

CREATE PROCEDURE USP_PAGINACION_AUTOMOVIL
	@NUMPAG	AS INT,
	@FILPAG	AS INT
AS
SELECT * FROM
AUTOMOVIL
WHERE ESTADO = 'A'
ORDER BY ID_AUTOMOVIL ASC
OFFSET @FILPAG*(@NUMPAG-1) ROWS
FETCH NEXT @FILPAG ROWS ONLY;
GO

--EXEC USP_PAGINACION_AUTOMOVIL 3,10
--GO

-- =========================================================================================
-- AUTHOR		:	KATHY DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA FILTRAR LA CANTIDAD DE REGISTROS EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_FILTRARCANTREG_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_FILTRARCANTREG_AUTOMOVIL
GO

CREATE PROCEDURE USP_FILTRARCANTREG_AUTOMOVIL
(
@CANTREG INT
)
AS
BEGIN
DECLARE @POSI INT
DECLARE @SQL NVARCHAR(500)
SET @POSI = @CANTREG % (SELECT COUNT(*) FROM AUTOMOVIL)
SET @SQL='SELECT TOP ' + CONVERT(NVARCHAR, @POSI) + ' * FROM AUTOMOVIL'
EXEC SP_EXECUTESQL @SQL
END
GO

--EXEC USP_FILTRARCANTREG_AUTOMOVIL 5
--GO