USE MASTER
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	20 DE JUNIO DEL 2017
-- DESCRIPTION	:	BASE DE DATOS USUARIO BD_VENTAS
---=====================================================================================
IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME='BD_VENTAS')
DROP DATABASE BD_VENTAS
GO
CREATE DATABASE BD_VENTAS
GO
USE BD_VENTAS
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	TABLA USUARIO
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='USUARIO' AND TYPE='U')
DROP TABLE USUARIO
GO

CREATE TABLE USUARIO
(
	ID_USUARIO			VARCHAR(9) NOT NULL,
	ID_PERSONAL			VARCHAR(9) NULL,
	USUARIO				VARCHAR(50) NOT NULL,
	PASSWORD			VARCHAR(50) NOT NULL,
	EMAIL				VARCHAR(50) NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_USUARIO PRIMARY KEY CLUSTERED (ID_USUARIO ASC) 
    ON [PRIMARY] 
) 
GO

INSERT INTO USUARIO(ID_USUARIO, ID_PERSONAL, USUARIO, PASSWORD, EMAIL,ESTADO, FECHA_REGISTRO, USUARIO_REGISTRO) VALUES ('USR000001','PER000001','ADMIN','ADMIN','ADMIN@GMAIL.COM','A','04/03/2017','ADMIN');
INSERT INTO USUARIO(ID_USUARIO, ID_PERSONAL, USUARIO, PASSWORD, EMAIL,ESTADO, FECHA_REGISTRO, USUARIO_REGISTRO) VALUES ('USR000002','PER000002','KATHY','PAOLA','KATHY@GMAIL.COM','A','01/07/2017','ADMIN');

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	TABLA AUTOMOVIL
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='AUTOMOVIL' AND TYPE='U')
DROP TABLE AUTOMOVIL
GO

CREATE TABLE AUTOMOVIL
(
	ID_AUTOMOVIL		VARCHAR(9) NOT NULL,
	ID_MARCA			VARCHAR(9) NOT NULL,
	MODELO				VARCHAR(50) NOT NULL,
	COLOR				VARCHAR(50) NOT NULL,
	PRECIO				DECIMAL(15,2) NOT NULL,
	STOCK				INT NOT NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_AUTOMOVIL PRIMARY KEY CLUSTERED (ID_AUTOMOVIL ASC) 
    ON [PRIMARY] 
) 
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	07 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA FILTRAR REGISTROS EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_FILTRAR_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_FILTRAR_AUTOMOVIL
GO

CREATE PROCEDURE USP_FILTRAR_AUTOMOVIL
		@ID_MARCA	VARCHAR(9),
		@MODELO		VARCHAR(50)		 
AS
SELECT	@MODELO = '%'+ LTRIM(RTRIM(@MODELO)) + '%';
SELECT	ID_AUTOMOVIL,
		ID_MARCA,
		MODELO,
		COLOR,
		PRECIO			
FROM	AUTOMOVIL
WHERE	ESTADO = 'A' AND 
		ID_MARCA=@ID_MARCA AND
		MODELO LIKE @MODELO
GO

--EXEC USP_FILTRAR_AUTOMOVIL 'MAR000001','C'
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA INSERTAR REGISTROS EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_INSERTAR_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_INSERTAR_AUTOMOVIL
GO

CREATE PROCEDURE USP_INSERTAR_AUTOMOVIL
	@ID_AUTOMOVIL		AS VARCHAR(9),
	@ID_MARCA			AS VARCHAR(9),
	@MODELO				AS VARCHAR(9),
	@COLOR				AS VARCHAR(32),
	@PRECIO				AS DECIMAL(15,2),
	@STOCK				AS INT,
	@ESTADO				AS CHAR(1),
	@FECHA_REGISTRO		AS VARCHAR(10),
	@USUARIO_REGISTRO	AS VARCHAR(9)
AS
BEGIN
INSERT INTO AUTOMOVIL
	(
	ID_AUTOMOVIL,
	ID_MARCA,
	MODELO,
	COLOR,
	PRECIO,
	STOCK,
	ESTADO,
	FECHA_REGISTRO,
	USUARIO_REGISTRO
	) 
	VALUES	
	(	
	@ID_AUTOMOVIL,
	@ID_MARCA,
	@MODELO,
	@COLOR,
	@PRECIO,
	@STOCK,
	@ESTADO,
	@FECHA_REGISTRO,
	@USUARIO_REGISTRO
	)
END
GO


-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	TABLA MARCAS
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='MARCA' AND TYPE='U')
DROP TABLE MARCA
GO

CREATE TABLE MARCA
(
	ID_MARCA			VARCHAR(9) NOT NULL,
	NOMBRE				VARCHAR(30) NOT NULL,
	NACIONALIDAD		VARCHAR(9) NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_MARCA PRIMARY KEY CLUSTERED (ID_MARCA ASC) 
    ON [PRIMARY] 
)
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	04 DE JULIO DEL 2017
-- DESCRIPTION	:	TABLA CLIENTE
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='CLIENTE' AND TYPE='U')
DROP TABLE CLIENTE
GO

CREATE TABLE CLIENTE
(
	ID_CLIENTE			VARCHAR(9) NOT NULL,
	PRI_NOMBRE			VARCHAR(50) NULL,
	SEG_NOMBRE			VARCHAR(50) NULL,
	PRI_APELLIDO		VARCHAR(50) NULL,
	SEG_APELLIDO		VARCHAR(50) NULL,
	RAZON_SOCIAL		VARCHAR(100) NULL,
	NOMBRE_COMERCIAL	VARCHAR(100) NULL,
	TIPO_DOCUMENTO		VARCHAR(80) NULL,
	NUMERO_DOCUMENTO	VARCHAR(80) NULL,
	NUMERO_RUC			VARCHAR(11) NULL,
	FECHA_NACIMIENTO	VARCHAR(10) NULL,
	TIPO_CLIENTE		VARCHAR(50) NOT NULL,
	CLASE_CLIENTE		VARCHAR(50) NOT NULL,
	ID_UBIGEO			VARCHAR(6) NULL,
	DIRECCION			VARCHAR(100) NOT NULL,
	ID_PAIS				VARCHAR(6) NOT NULL,
	TELEFONO_FIJO		VARCHAR(7) NULL,
	CELULAR				VARCHAR(9) NULL,
	EMAIL				VARCHAR(50) NULL,
	SEXO				CHAR(1) NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_CLIENTES PRIMARY KEY CLUSTERED (ID_CLIENTE ASC) 
    ON [PRIMARY] 
) 
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	05 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA FILTRAR REGISTROS EN lA TABLA CLIENTE
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_FILTRAR_CLIENTE' AND TYPE='P')
DROP PROC USP_FILTRAR_CLIENTE
GO

CREATE PROCEDURE USP_FILTRAR_CLIENTE
		@NOMBRES_RAZSOC VARCHAR(100) 
AS
SELECT	@NOMBRES_RAZSOC = '%'+ LTRIM(RTRIM(@NOMBRES_RAZSOC)) + '%';
SELECT	ID_CLIENTE, 
		PRI_NOMBRE+' '+SEG_NOMBRE+' '+PRI_APELLIDO+' '+SEG_APELLIDO AS NOMBRES_RAZSOC,
		NUMERO_DOCUMENTO AS DNIRUC,
		DIRECCION
FROM CLIENTE
WHERE TIPO_CLIENTE='NATURAL' AND PRI_NOMBRE+' '+SEG_NOMBRE+' '+PRI_APELLIDO+' '+SEG_APELLIDO LIKE @NOMBRES_RAZSOC
UNION ALL
SELECT	ID_CLIENTE, 
		RAZON_SOCIAL,
		NUMERO_RUC,
		DIRECCION 
FROM CLIENTE
WHERE TIPO_CLIENTE='JURIDICO' AND RAZON_SOCIAL LIKE @NOMBRES_RAZSOC
GO

--EXEC USP_FILTRAR_CLIENTE 'R'
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	04 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA INSERTAR REGISTROS EN lA TABLA CLIENTE
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_INSERTAR_CLIENTE' AND TYPE='P')
DROP PROC USP_INSERTAR_CLIENTE
GO

CREATE PROCEDURE USP_INSERTAR_CLIENTE
	@ID_CLIENTE			AS VARCHAR(9),
	@PRI_NOMBRE			AS VARCHAR(50),
	@SEG_NOMBRE			AS VARCHAR(50),
	@PRI_APELLIDO		AS VARCHAR(50),
	@SEG_APELLIDO		AS VARCHAR(50),
	@RAZON_SOCIAL		AS VARCHAR(100),
	@NOMBRE_COMERCIAL	AS VARCHAR(100),
	@TIPO_DOCUMENTO		AS VARCHAR(80),
	@NUMERO_DOCUMENTO	AS VARCHAR(80),
	@NUMERO_RUC			AS VARCHAR(11),
	@FECHA_NACIMIENTO	AS VARCHAR(10),
	@TIPO_CLIENTE		AS VARCHAR(50),
	@CLASE_CLIENTE		AS VARCHAR(50),
	@ID_UBIGEO			AS VARCHAR(6),
	@DIRECCION			AS VARCHAR(100),
	@ID_PAIS			AS VARCHAR(6),
	@TELEFONO_FIJO		AS VARCHAR(7),
	@CELULAR			AS VARCHAR(9),
	@EMAIL				AS VARCHAR(50),
	@SEXO				AS CHAR(1),
	@ESTADO				AS CHAR(1),
	@FECHA_REGISTRO		AS VARCHAR(10),
	@USUARIO_REGISTRO	AS VARCHAR(9)
AS
BEGIN
INSERT INTO CLIENTE
	(
	ID_CLIENTE,
	PRI_NOMBRE,
	SEG_NOMBRE,
	PRI_APELLIDO,
	SEG_APELLIDO,
	RAZON_SOCIAL,
	NOMBRE_COMERCIAL,
	TIPO_DOCUMENTO,
	NUMERO_DOCUMENTO,
	NUMERO_RUC,
	FECHA_NACIMIENTO,
	TIPO_CLIENTE,
	CLASE_CLIENTE,
	ID_UBIGEO,
	DIRECCION,
	ID_PAIS,
	TELEFONO_FIJO,
	CELULAR,
	EMAIL,
	SEXO,
	ESTADO,
	FECHA_REGISTRO,
	USUARIO_REGISTRO
	) 
	VALUES	
	(	
	@ID_CLIENTE,
	@PRI_NOMBRE,
	@SEG_NOMBRE,
	@PRI_APELLIDO,
	@SEG_APELLIDO,
	@RAZON_SOCIAL,
	@NOMBRE_COMERCIAL,
	@TIPO_DOCUMENTO,
	@NUMERO_DOCUMENTO,
	@NUMERO_RUC,
	@FECHA_NACIMIENTO,
	@TIPO_CLIENTE,
	@CLASE_CLIENTE,
	@ID_UBIGEO,
	@DIRECCION,
	@ID_PAIS,
	@TELEFONO_FIJO,
	@CELULAR,
	@EMAIL,
	@SEXO,
	@ESTADO,
	@FECHA_REGISTRO,
	@USUARIO_REGISTRO
	)
END
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	04 DE JULIO DEL 2017
-- DESCRIPTION	:	TABLA UBIGEO
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='UBIGEO' AND TYPE='U')
DROP TABLE UBIGEO
GO

CREATE TABLE UBIGEO
(
	ID_UBIGEO			VARCHAR(6) NOT NULL,
	DEPARTAMENTO		VARCHAR(50) NULL, 
	PROVINCIA			VARCHAR(50) NULL,
	DISTRITO			VARCHAR(50) NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_UBIGEO PRIMARY KEY CLUSTERED (ID_UBIGEO ASC) 
    ON [PRIMARY] 
) 
GO

SELECT ID_UBIGEO, DEPARTAMENTO FROM UBIGEO WHERE SUBSTRING(ID_UBIGEO,3,4) = '0000'

INSERT INTO UBIGEO (ID_UBIGEO, DEPARTAMENTO, PROVINCIA, DISTRITO, ESTADO, FECHA_REGISTRO, USUARIO_REGISTRO)
SELECT IdUbigeo, Departamento, Provincia, Distrito, Estado, Fec_Reg, Usuario_Reg FROM [dbo].[Ubigeo$];

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	09 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LOS DEPARTAMENTOS
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_DEPARTAMENTO_CONSULTA_LISTA' AND TYPE='P')
DROP PROC USP_DEPARTAMENTO_CONSULTA_LISTA
GO

CREATE PROCEDURE USP_DEPARTAMENTO_CONSULTA_LISTA 
AS
SELECT	ID_UBIGEO, 
		DEPARTAMENTO 
FROM UBIGEO 
WHERE SUBSTRING(ID_UBIGEO,3,4) = '0000'
		AND ESTADO = 'A'
GO

--EXEC USP_DEPARTAMENTO_CONSULTA_LISTA
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	09 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LAS PROVINCIAS
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_PROVINCIA_CONSULTA_LISTA' AND TYPE='P')
DROP PROC USP_PROVINCIA_CONSULTA_LISTA
GO

CREATE PROCEDURE USP_PROVINCIA_CONSULTA_LISTA
@ID_DEPARTAMENTO	AS VARCHAR(2) 
AS

SELECT	ID_UBIGEO, 
		PROVINCIA FROM UBIGEO 
WHERE	SUBSTRING(ID_UBIGEO,5,2) = '00' 
		AND SUBSTRING(ID_UBIGEO,1,2) = @ID_DEPARTAMENTO 
		AND SUBSTRING(ID_UBIGEO,3,2) <> '00' 
		AND ESTADO = 'A'
GO

--EXEC USP_PROVINCIA_CONSULTA_LISTA '15'
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	09 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LOS DISTRITOS
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_DISTRITO_CONSULTA_LISTA' AND TYPE='P')
DROP PROC USP_DISTRITO_CONSULTA_LISTA
GO

CREATE PROCEDURE USP_DISTRITO_CONSULTA_LISTA
@ID_DEPARTAMENTO	AS VARCHAR(2),
@ID_PROVINCIA		AS VARCHAR(2) 
AS

SELECT	ID_UBIGEO, 
		DISTRITO 
FROM	UBIGEO 
WHERE	SUBSTRING(ID_UBIGEO,1,2) = @ID_DEPARTAMENTO 
		AND SUBSTRING(ID_UBIGEO,3,2) = @ID_PROVINCIA AND 
		SUBSTRING(ID_UBIGEO,5,2) <> '00'
		AND ESTADO = 'A'
GO

--EXEC USP_DISTRITO_CONSULTA_LISTA '15','01'
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	04 DE JULIO DEL 2017
-- DESCRIPTION	:	TABLA PAIS
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='PAIS' AND TYPE='U')
DROP TABLE PAIS
GO

CREATE TABLE PAIS
(
	ID_PAIS				VARCHAR(6) NOT NULL,
	ISO					VARCHAR(2) NOT NULL,
	NOMBRE				VARCHAR(100) NOT NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL,

	CONSTRAINT PK_PAIS PRIMARY KEY CLUSTERED (ID_PAIS ASC) 
    ON [PRIMARY] 
) 
GO


-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	09 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LOS PAISES
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_PAIS_CONSULTA_LISTA' AND TYPE='P')
DROP PROC USP_PAIS_CONSULTA_LISTA
GO

CREATE PROCEDURE USP_PAIS_CONSULTA_LISTA 
AS
SELECT	ID_PAIS, 
		NOMBRE 
FROM PAIS 
WHERE ESTADO = 'A'
GO

--EXEC USP_PAIS_CONSULTA_LISTA 
--GO



INSERT INTO PAIS VALUES('PAI001', 'AF', 'AFGANISTÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI002', 'AX', 'ISLAS GLAND', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI003', 'AL', 'ALBANIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI004', 'DE', 'ALEMANIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI005', 'AD', 'ANDORRA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI006', 'AO', 'ANGOLA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI007', 'AI', 'ANGUILLA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI008', 'AQ', 'ANTÁRTIDA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI009', 'AG', 'ANTIGUA Y BARBUDA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI010', 'AN', 'ANTILLAS HOLANDESAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI011', 'SA', 'ARABIA SAUDÍ', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI012', 'DZ', 'ARGELIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI013', 'AR', 'ARGENTINA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI014', 'AM', 'ARMENIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI015', 'AW', 'ARUBA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI016', 'AU', 'AUSTRALIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI017', 'AT', 'AUSTRIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI018', 'AZ', 'AZERBAIYÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI019', 'BS', 'BAHAMAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI020', 'BH', 'BAHRÉIN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI021', 'BD', 'BANGLADESH', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI022', 'BB', 'BARBADOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI023', 'BY', 'BIELORRUSIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI024', 'BE', 'BÉLGICA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI025', 'BZ', 'BELICE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI026', 'BJ', 'BENIN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI027', 'BM', 'BERMUDAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI028', 'BT', 'BHUTÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI029', 'BO', 'BOLIVIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI030', 'BA', 'BOSNIA Y HERZEGOVINA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI031', 'BW', 'BOTSUANA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI032', 'BV', 'ISLA BOUVET', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI033', 'BR', 'BRASIL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI034', 'BN', 'BRUNÉI', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI035', 'BG', 'BULGARIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI036', 'BF', 'BURKINA FASO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI037', 'BI', 'BURUNDI', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI038', 'CV', 'CABO VERDE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI039', 'KY', 'ISLAS CAIMÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI040', 'KH', 'CAMBOYA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI041', 'CM', 'CAMERÚN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI042', 'CA', 'CANADÁ', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI043', 'CF', 'REPÚBLICA CENTROAFRICANA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI044', 'TD', 'CHAD', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI045', 'CZ', 'REPÚBLICA CHECA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI046', 'CL', 'CHILE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI047', 'CN', 'CHINA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI048', 'CY', 'CHIPRE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI049', 'CX', 'ISLA DE NAVIDAD', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI050', 'VA', 'CIUDAD DEL VATICANO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI051', 'CC', 'ISLAS COCOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI052', 'CO', 'COLOMBIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI053', 'KM', 'COMORAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI054', 'CD', 'REPÚBLICA DEMOCRÁTICA DEL CONGO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI055', 'CG', 'CONGO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI056', 'CK', 'ISLAS COOK', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI057', 'KP', 'COREA DEL NORTE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI058', 'KR', 'COREA DEL SUR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI059', 'CI', 'COSTA DE MARFIL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI060', 'CR', 'COSTA RICA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI061', 'HR', 'CROACIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI062', 'CU', 'CUBA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI063', 'DK', 'DINAMARCA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI064', 'DM', 'DOMINICA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI065', 'DO', 'REPÚBLICA DOMINICANA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI066', 'EC', 'ECUADOR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI067', 'EG', 'EGIPTO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI068', 'SV', 'EL SALVADOR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI069', 'AE', 'EMIRATOS ÁRABES UNIDOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI070', 'ER', 'ERITREA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI071', 'SK', 'ESLOVAQUIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI072', 'SI', 'ESLOVENIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI073', 'ES', 'ESPAÑA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI074', 'UM', 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI075', 'US', 'ESTADOS UNIDOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI076', 'EE', 'ESTONIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI077', 'ET', 'ETIOPÍA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI078', 'FO', 'ISLAS FEROE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI079', 'PH', 'FILIPINAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI080', 'FI', 'FINLANDIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI081', 'FJ', 'FIYI', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI082', 'FR', 'FRANCIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI083', 'GA', 'GABÓN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI084', 'GM', 'GAMBIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI085', 'GE', 'GEORGIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI086', 'GS', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI087', 'GH', 'GHANA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI088', 'GI', 'GIBRALTAR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI089', 'GD', 'GRANADA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI090', 'GR', 'GRECIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI091', 'GL', 'GROENLANDIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI092', 'GP', 'GUADALUPE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI093', 'GU', 'GUAM', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI094', 'GT', 'GUATEMALA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI095', 'GF', 'GUAYANA FRANCESA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI096', 'GN', 'GUINEA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI097', 'GQ', 'GUINEA ECUATORIAL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI098', 'GW', 'GUINEA-BISSAU', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI099', 'GY', 'GUYANA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI100', 'HT', 'HAITÍ', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI101', 'HM', 'ISLAS HEARD Y MCDONALD', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI102', 'HN', 'HONDURAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI103', 'HK', 'HONG KONG', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI104', 'HU', 'HUNGRÍA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI105', 'IN', 'INDIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI106', 'ID', 'INDONESIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI107', 'IR', 'IRÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI108', 'IQ', 'IRAQ', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI109', 'IE', 'IRLANDA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI110', 'IS', 'ISLANDIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI111', 'IL', 'ISRAEL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI112', 'IT', 'ITALIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI113', 'JM', 'JAMAICA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI114', 'JP', 'JAPÓN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI115', 'JO', 'JORDANIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI116', 'KZ', 'KAZAJSTÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI117', 'KE', 'KENIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI118', 'KG', 'KIRGUISTÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI119', 'KI', 'KIRIBATI', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI120', 'KW', 'KUWAIT', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI121', 'LA', 'LAOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI122', 'LS', 'LESOTHO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI123', 'LV', 'LETONIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI124', 'LB', 'LÍBANO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI125', 'LR', 'LIBERIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI126', 'LY', 'LIBIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI127', 'LI', 'LIECHTENSTEIN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI128', 'LT', 'LITUANIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI129', 'LU', 'LUXEMBURGO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI130', 'MO', 'MACAO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI131', 'MK', 'ARY MACEDONIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI132', 'MG', 'MADAGASCAR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI133', 'MY', 'MALASIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI134', 'MW', 'MALAWI', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI135', 'MV', 'MALDIVAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI136', 'ML', 'MALÍ', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI137', 'MT', 'MALTA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI138', 'FK', 'ISLAS MALVINAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI139', 'MP', 'ISLAS MARIANAS DEL NORTE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI140', 'MA', 'MARRUECOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI141', 'MH', 'ISLAS MARSHALL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI142', 'MQ', 'MARTINICA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI143', 'MU', 'MAURICIO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI144', 'MR', 'MAURITANIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI145', 'YT', 'MAYOTTE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI146', 'MX', 'MÉXICO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI147', 'FM', 'MICRONESIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI148', 'MD', 'MOLDAVIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI149', 'MC', 'MÓNACO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI150', 'MN', 'MONGOLIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI151', 'MS', 'MONTSERRAT', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI152', 'MZ', 'MOZAMBIQUE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI153', 'MM', 'MYANMAR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI154', 'NA', 'NAMIBIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI155', 'NR', 'NAURU', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI156', 'NP', 'NEPAL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI157', 'NI', 'NICARAGUA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI158', 'NE', 'NÍGER', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI159', 'NG', 'NIGERIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI160', 'NU', 'NIUE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI161', 'NF', 'ISLA NORFOLK', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI162', 'NO', 'NORUEGA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI163', 'NC', 'NUEVA CALEDONIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI164', 'NZ', 'NUEVA ZELANDA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI165', 'OM', 'OMÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI166', 'NL', 'PAÍSES BAJOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI167', 'PK', 'PAKISTÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI168', 'PW', 'PALAU', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI169', 'PS', 'PALESTINA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI170', 'PA', 'PANAMÁ', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI171', 'PG', 'PAPÚA NUEVA GUINEA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI172', 'PY', 'PARAGUAY', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI173', 'PE', 'PERÚ', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI174', 'PN', 'ISLAS PITCAIRN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI175', 'PF', 'POLINESIA FRANCESA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI176', 'PL', 'POLONIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI177', 'PT', 'PORTUGAL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI178', 'PR', 'PUERTO RICO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI179', 'QA', 'QATAR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI180', 'GB', 'REINO UNIDO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI181', 'RE', 'REUNIÓN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI182', 'RW', 'RUANDA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI183', 'RO', 'RUMANIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI184', 'RU', 'RUSIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI185', 'EH', 'SAHARA OCCIDENTAL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI186', 'SB', 'ISLAS SALOMÓN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI187', 'WS', 'SAMOA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI188', 'AS', 'SAMOA AMERICANA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI189', 'KN', 'SAN CRISTÓBAL Y NEVIS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI190', 'SM', 'SAN MARINO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI191', 'PM', 'SAN PEDRO Y MIQUELÓN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI192', 'VC', 'SAN VICENTE Y LAS GRANADINAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI193', 'SH', 'SANTA HELENA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI194', 'LC', 'SANTA LUCÍA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI195', 'ST', 'SANTO TOMÉ Y PRÍNCIPE', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI196', 'SN', 'SENEGAL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI197', 'CS', 'SERBIA Y MONTENEGRO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI198', 'SC', 'SEYCHELLES', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI199', 'SL', 'SIERRA LEONA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI200', 'SG', 'SINGAPUR', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI201', 'SY', 'SIRIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI202', 'SO', 'SOMALIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI203', 'LK', 'SRI LANKA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI204', 'SZ', 'SUAZILANDIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI205', 'ZA', 'SUDÁFRICA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI206', 'SD', 'SUDÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI207', 'SE', 'SUECIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI208', 'CH', 'SUIZA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI209', 'SR', 'SURINAM', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI210', 'SJ', 'SVALBARD Y JAN MAYEN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI211', 'TH', 'TAILANDIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI212', 'TW', 'TAIWÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI213', 'TZ', 'TANZANIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI214', 'TJ', 'TAYIKISTÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI215', 'IO', 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI216', 'TF', 'TERRITORIOS AUSTRALES FRANCESES', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI217', 'TL', 'TIMOR ORIENTAL', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI218', 'TG', 'TOGO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI219', 'TK', 'TOKELAU', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI220', 'TO', 'TONGA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI221', 'TT', 'TRINIDAD Y TOBAGO', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI222', 'TN', 'TÚNEZ', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI223', 'TC', 'ISLAS TURCAS Y CAICOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI224', 'TM', 'TURKMENISTÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI225', 'TR', 'TURQUÍA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI226', 'TV', 'TUVALU', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI227', 'UA', 'UCRANIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI228', 'UG', 'UGANDA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI229', 'UY', 'URUGUAY', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI230', 'UZ', 'UZBEKISTÁN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI231', 'VU', 'VANUATU', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI232', 'VE', 'VENEZUELA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI233', 'VN', 'VIETNAM', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI234', 'VG', 'ISLAS VÍRGENES BRITÁNICAS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI235', 'VI', 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI236', 'WF', 'WALLIS Y FUTUNA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI237', 'YE', 'YEMEN', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI238', 'DJ', 'YIBUTI', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI239', 'ZM', 'ZAMBIA', 'A', '07/09/2017' , 'ADMIN');
INSERT INTO PAIS VALUES('PAI240', 'ZW', 'ZIMBABUE', 'A', '07/09/2017' , 'ADMIN');

ALTER TABLE AUTOMOVIL 
	WITH CHECK 
	ADD CONSTRAINT FK_AUTOMOVIL_MARCA 
	FOREIGN KEY (ID_MARCA)
	REFERENCES MARCA (ID_MARCA)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
GO


ALTER TABLE CLIENTE  
	WITH CHECK 
	ADD  CONSTRAINT FK_CLIENTE_UBIGEO 
	FOREIGN KEY(ID_UBIGEO)
	REFERENCES UBIGEO (ID_UBIGEO)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
GO


ALTER TABLE CLIENTE  
	WITH CHECK 
	ADD  CONSTRAINT FK_CLIENTE_PAISE 
	FOREIGN KEY(ID_PAIS)
	REFERENCES PAIS (ID_PAIS)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
GO



-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LOGIN DE LOS USUARIOS
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_LOGIN_USUARIO' AND TYPE='P')
DROP PROC USP_LOGIN_USUARIO
GO

CREATE PROCEDURE USP_LOGIN_USUARIO
	@USUARIO	AS VARCHAR(50),
	@PASWORD	AS VARCHAR(50)
AS
SELECT	USUARIO,
		PASSWORD
FROM USUARIO
WHERE	USUARIO=@USUARIO AND 
		PASSWORD=@PASWORD AND 
		ESTADO = 'A'
GO
--EXEC USP_LOGIN_USUARIO 'ADMI1N1','ADMIN'
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LOS AUTOMOVILES
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_AUTOMOVIL_CONSULTA' AND TYPE='P')
DROP PROC USP_AUTO_CONSULTA
GO

CREATE PROCEDURE USP_AUTOMOVIL_CONSULTA AS

SELECT	ID_AUTOMOVIL,
		ID_MARCA,
		MODELO,
		COLOR,
		PRECIO,
		STOCK,
		ESTADO
FROM AUTOMOVIL
WHERE ESTADO = 'A'
GO

--EXEC USP_AUTOMOVIL_CONSULTA
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA GENERAR CODIGO DE AUTOMOVIL
-- =====================================================================================
---------------------------- GENERAR CODIGO DE AUTOMOVIL ------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_GENERARCODIGOAUTOMOVIL' AND TYPE='P')
DROP PROC USP_GENERARCODIGOAUTOMOVIL
GO
CREATE proc USP_GENERARCODIGOAUTOMOVIL
AS
DECLARE @CODIGO CHAR(9)
SET @CODIGO=(SELECT MAX(ID_AUTOMOVIL) AS CODIGO FROM AUTOMOVIL)
SET @CODIGO='AUT'+RIGHT('00000'+LTRIM(RIGHT(ISNULL(@CODIGO,'00000'),6)+1),6)
SELECT @CODIGO AS CODIGO
GO

--EXEC USP_GENERARCODIGOAUTOMOVIL
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA GENERAR CODIGO DE MARCA
-- =====================================================================================
---------------------------- GENERAR CODIGO DE MARCA ------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_GENERARCODIGOMARCA' AND TYPE='P')
DROP PROC USP_GENERARCODIGOMARCA
GO
CREATE proc USP_GENERARCODIGOMARCA
AS
DECLARE @CODIGO CHAR(9)
SET @CODIGO=(SELECT MAX(ID_MARCA) AS CODIGO FROM MARCA)
SET @CODIGO='MAR'+RIGHT('00000'+LTRIM(RIGHT(ISNULL(@CODIGO,'00000'),6)+1),6)
SELECT @CODIGO AS CODIGO
GO

--EXEC USP_GENERARCODIGOMARCA
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA GENERAR CODIGO DE CLIENTE
-- =====================================================================================
---------------------------- GENERAR CODIGO DE CLIENTE ------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_GENERARCODIGOCLIENTE' AND TYPE='P')
DROP PROC USP_GENERARCODIGOCLIENTE
GO
CREATE proc USP_GENERARCODIGOCLIENTE
AS
DECLARE @CODIGO CHAR(9)
SET @CODIGO=(SELECT MAX(ID_CLIENTE) AS CODIGO FROM CLIENTE)
SET @CODIGO='CLI'+RIGHT('00000'+LTRIM(RIGHT(ISNULL(@CODIGO,'00000'),6)+1),6)
SELECT @CODIGO AS CODIGO
GO

--EXEC USP_GENERARCODIGOCLIENTE
--GO



-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LAS MARCAS
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_MARCA_CONSULTA_LISTA' AND TYPE='P')
DROP PROC USP_MARCA_CONSULTA_LISTA
GO

CREATE PROCEDURE USP_MARCA_CONSULTA_LISTA 
AS
SELECT	ID_MARCA,
		NOMBRE
FROM MARCA
WHERE ESTADO = 'A'
GO

--EXEC USP_MARCA_CONSULTA_LISTA
--GO




-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA ACTUALIZAR REGISTROS EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_UPDATE_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_UPDATE_AUTOMOVIL
GO

CREATE PROCEDURE USP_UPDATE_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9),
	@ID_MARCA		AS VARCHAR(9),
	@MODELO			AS VARCHAR(9),
	@COLOR			AS VARCHAR(32),
	@PRECIO			AS DECIMAL(15,2),
	@STOCK			AS INT
AS
UPDATE AUTOMOVIL
   SET	ID_MARCA = @ID_MARCA,
		MODELO = @MODELO,
		COLOR = @COLOR,
		PRECIO = @PRECIO,
		STOCK = @STOCK
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL
GO


-- =================================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA ELIMINAR UN REGISTROS EN lA TABLA AUTOMOVIL - ESTADO INACTIVO
-- =================================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_DELETE_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_DELETE_AUTOMOVIL
GO

CREATE PROCEDURE USP_DELETE_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9)
AS
UPDATE AUTOMOVIL
   SET	ESTADO = 'I'
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL
GO

--EXEC USP_DELETE_AUTOMOVIL 'AUT000001'
--GO


 -- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA BUSCAR UN REGISTRO EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_BUSCAR_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_BUSCAR_AUTOMOVIL
GO

CREATE PROCEDURE USP_BUSCAR_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9)
AS
SELECT	ID_AUTOMOVIL,
		ID_MARCA,
		MODELO,
		COLOR,
		PRECIO,
		STOCK,
		ESTADO,
		FECHA_REGISTRO,
		USUARIO_REGISTRO
FROM AUTOMOVIL
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL AND ESTADO = 'A'
GO

--EXEC USP_BUSCAR_AUTOMOVIL 'AUT000001'
--GO

-- =========================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA MOSTRAR LA CANTIDAD DE REGISTROS EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_TOTAL_REGISTROS_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_TOTAL_REGISTROS_AUTOMOVIL
GO

CREATE PROCEDURE USP_TOTAL_REGISTROS_AUTOMOVIL 
AS
SELECT COUNT(*) AS CANTREG
FROM AUTOMOVIL
WHERE ESTADO = 'A'
GO

--EXEC USP_TOTAL_REGISTROS_AUTOMOVIL
--GO

-- =========================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LA PAGINACIÓN EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_PAGINACION_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_PAGINACION_AUTOMOVIL
GO

CREATE PROCEDURE USP_PAGINACION_AUTOMOVIL
	@NUMPAG	AS INT,
	@FILPAG	AS INT
AS
SELECT * FROM
AUTOMOVIL
WHERE ESTADO = 'A'
ORDER BY ID_AUTOMOVIL ASC
OFFSET @FILPAG*(@NUMPAG-1) ROWS
FETCH NEXT @FILPAG ROWS ONLY;
GO

--EXEC USP_PAGINACION_AUTOMOVIL 1,10
--GO

-- =========================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA FILTRAR LA CANTIDAD DE REGISTROS EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_FILTRARCANTREG_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_FILTRARCANTREG_AUTOMOVIL
GO

CREATE PROCEDURE USP_FILTRARCANTREG_AUTOMOVIL
	@POSI AS INT
AS
SELECT TOP (@POSI) * FROM AUTOMOVIL 
WHERE ESTADO = 'A'
GO

--EXEC USP_FILTRARCANTREG_AUTOMOVIL 10
--GO


