USE MASTER
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	20 DE JUNIO DEL 2017
-- DESCRIPTION	:	BASE DE DATOS USUARIO BD_VENTAS
---=====================================================================================
IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME='BD_VENTAS')
DROP DATABASE BD_VENTAS
GO
CREATE DATABASE BD_VENTAS
GO
USE BD_VENTAS
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	TABLA USUARIO
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='USUARIO' AND TYPE='U')
DROP TABLE USUARIO
GO

CREATE TABLE USUARIO
(
	ID_USUARIO			VARCHAR(9) NOT NULL,
	ID_PERSONAL			VARCHAR(9) NULL,
	USUARIO				VARCHAR(50) NOT NULL,
	PASSWORD			VARCHAR(50) NOT NULL,
	EMAIL				VARCHAR(50) NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_USUARIO PRIMARY KEY CLUSTERED (ID_USUARIO ASC) 
    ON [PRIMARY] 
) 
GO

--INSERT INTO USUARIO(ID_USUARIO, ID_PERSONAL, USUARIO, PASSWORD, EMAIL,ESTADO, FECHA_REGISTRO) VALUES ('USR000001','PER000001','ADMIN','ADMIN','ADMIN@GMAIL.COM','A','04/03/2017');
--INSERT INTO USUARIO(ID_USUARIO, ID_PERSONAL, USUARIO, PASSWORD, EMAIL,ESTADO, FECHA_REGISTRO) VALUES ('USR000002','PER000002','KATHY','PAOLA','KATHY@GMAIL.COM','A','01/07/2017');

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	TABLA AUTOMOVIL
---=====================================================================================
CREATE TABLE AUTOMOVIL
(
	ID_AUTOMOVIL		VARCHAR(9) NOT NULL,
	ID_MARCA			VARCHAR(9) NOT NULL,
	MODELO				VARCHAR(9) NOT NULL,
	COLOR				VARCHAR(32) NOT NULL,
	PRECIO				DECIMAL(15,2) NOT NULL,
	STOCK				INT NOT NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_AUTOMOVIL PRIMARY KEY CLUSTERED (ID_AUTOMOVIL ASC) 
    ON [PRIMARY] 
) 
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	TABLA MARCAS
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='MARCA' AND TYPE='U')
DROP TABLE MARCA
GO

CREATE TABLE MARCA
(
	ID_MARCA			VARCHAR(9) NOT NULL,
	NOMBRE				VARCHAR(30) NOT NULL,
	NACIONALIDAD		VARCHAR(9) NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_MARCA PRIMARY KEY CLUSTERED (ID_MARCA ASC) 
    ON [PRIMARY] 
)
GO 


-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	04 DE JULIO DEL 2017
-- DESCRIPTION	:	TABLA CLIENTE
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='CLIENTE' AND TYPE='U')
DROP TABLE CLIENTE
GO

CREATE TABLE CLIENTE
(
	ID_CLIENTE			VARCHAR(9) NOT NULL,
	PRI_NOMBRE			VARCHAR(50) NULL,
	SEG_NOMBRE			VARCHAR(50) NULL,
	PRI_APELLIDO		VARCHAR(50) NULL,
	SEG_APELLIDO		VARCHAR(50) NULL,
	RAZON_SOCIAL		VARCHAR(100) NULL,
	NOMBRE_COMERCIAL	VARCHAR(100) NULL,
	TIPO_DOCUMENTO		VARCHAR(80) NULL,
	NUMERO_DOCUMENTO	VARCHAR(80) NULL,
	NUMERO_RUC			VARCHAR(11) NOT NULL,
	FECHA_NACIMIENTO	DATETIME NULL,
	TIPO_CLIENTE		VARCHAR(50) NOT NULL,
	CLASE_CLIENTE		VARCHAR(50) NOT NULL,
	ID_UBIGEO			VARCHAR(6) NOT NULL,
	DIRECCION			VARCHAR(100) NOT NULL,
	ID_PAIS				VARCHAR(9) NOT NULL,
	TELEFONO_FIJO		VARCHAR(7) NULL,
	CELULAR				VARCHAR(9) NULL,
	EMAIL				VARCHAR(50) NULL,
	SEXO				CHAR(1) NOT NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_CLIENTES PRIMARY KEY CLUSTERED (ID_CLIENTE ASC) 
    ON [PRIMARY] 
) 
GO



-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	04 DE JULIO DEL 2017
-- DESCRIPTION	:	TABLA UBIGEO
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='UBIGEO' AND TYPE='U')
DROP TABLE UBIGEO
GO

CREATE TABLE UBIGEO
(
	ID_UBIGEO			VARCHAR(6) NOT NULL,
	DEPARTAMENTO		VARCHAR(50) NULL, 
	PROVINCIA			VARCHAR(50) NULL,
	DISTRITO			VARCHAR(50) NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_UBIGEO PRIMARY KEY CLUSTERED (ID_UBIGEO ASC) 
    ON [PRIMARY] 
) 
GO


-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	04 DE JULIO DEL 2017
-- DESCRIPTION	:	TABLA PAIS
---=====================================================================================
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='PAIS' AND TYPE='U')
DROP TABLE PAIS
GO

CREATE TABLE PAIS
(
	ID_PAIS				VARCHAR(9) NOT NULL,
	ISO_1				VARCHAR(3) NOT NULL,
	ISO_2				VARCHAR(3) NOT NULL,
	ISO_3				VARCHAR(3) NOT NULL,
	NOMBRE				VARCHAR(100) NOT NULL,
	ESTADO				CHAR(1) NOT NULL,
	FECHA_REGISTRO		VARCHAR(10) NOT NULL,
	USUARIO_REGISTRO	VARCHAR(9) NOT NULL

	CONSTRAINT PK_PAIS PRIMARY KEY CLUSTERED (ID_PAIS ASC) 
    ON [PRIMARY] 
) 
GO


ALTER TABLE AUTOMOVIL 
	WITH CHECK 
	ADD CONSTRAINT FK_AUTOMOVIL_MARCA 
	FOREIGN KEY (ID_MARCA)
	REFERENCES MARCA (ID_MARCA)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
GO


ALTER TABLE CLIENTE  
	WITH CHECK 
	ADD  CONSTRAINT FK_CLIENTE_UBIGEO 
	FOREIGN KEY(ID_UBIGEO)
	REFERENCES UBIGEO (ID_UBIGEO)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
GO


ALTER TABLE CLIENTE  
	WITH CHECK 
	ADD  CONSTRAINT FK_CLIENTE_PAISE 
	FOREIGN KEY(ID_PAIS)
	REFERENCES PAISE (ID_PAIS)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
GO



-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LOGIN DE LOS USUARIOS
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_LOGIN_USUARIO' AND TYPE='P')
DROP PROC USP_LOGIN_USUARIO
GO

CREATE PROCEDURE USP_LOGIN_USUARIO
	@USUARIO	AS VARCHAR(50),
	@PASWORD	AS VARCHAR(50)
AS
SELECT	USUARIO,
		PASSWORD
FROM USUARIO
WHERE	USUARIO=@USUARIO AND 
		PASSWORD=@PASWORD AND 
		ESTADO = 'A'
GO
--EXEC USP_LOGIN_USUARIO 'ADMI1N1','ADMIN'
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LOS AUTOMOVILES
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_AUTOMOVIL_CONSULTA' AND TYPE='P')
DROP PROC USP_AUTO_CONSULTA
GO

CREATE PROCEDURE USP_AUTOMOVIL_CONSULTA AS

SELECT	ID_AUTOMOVIL,
		ID_MARCA,
		MODELO,
		COLOR,
		PRECIO,
		STOCK,
		ESTADO
FROM AUTOMOVIL
WHERE ESTADO = 'A'
GO

--EXEC USP_AUTOMOVIL_CONSULTA
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA GENERAR CODIGO DE AUTOMOVIL
-- =====================================================================================
---------------------------- GENERAR CODIGO DE AUTOMOVIL ------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_GENERARCODIGOAUTOMOVIL' AND TYPE='P')
DROP PROC USP_GENERARCODIGOAUTOMOVIL
GO
CREATE proc USP_GENERARCODIGOAUTOMOVIL
AS
DECLARE @CODIGO CHAR(9)
SET @CODIGO=(SELECT MAX(ID_AUTOMOVIL) AS CODIGO FROM AUTOMOVIL)
SET @CODIGO='AUT'+RIGHT('00000'+LTRIM(RIGHT(ISNULL(@CODIGO,'00000'),6)+1),6)
SELECT @CODIGO AS CODIGO
GO

--EXEC USP_GENERARCODIGOAUTOMOVIL
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA GENERAR CODIGO DE MARCA
-- =====================================================================================
---------------------------- GENERAR CODIGO DE MARCA ------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_GENERARCODIGOMARCA' AND TYPE='P')
DROP PROC USP_GENERARCODIGOMARCA
GO
CREATE proc USP_GENERARCODIGOMARCA
AS
DECLARE @CODIGO CHAR(9)
SET @CODIGO=(SELECT MAX(ID_MARCA) AS CODIGO FROM MARCA)
SET @CODIGO='MAR'+RIGHT('00000'+LTRIM(RIGHT(ISNULL(@CODIGO,'00000'),6)+1),6)
SELECT @CODIGO AS CODIGO
GO

--EXEC USP_GENERARCODIGOMARCA
--GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA GENERAR CODIGO DE CLIENTE
-- =====================================================================================
---------------------------- GENERAR CODIGO DE CLIENTE ------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_GENERARCODIGOCLIENTE' AND TYPE='P')
DROP PROC USP_GENERARCODIGOCLIENTE
GO
CREATE proc USP_GENERARCODIGOCLIENTE
AS
DECLARE @CODIGO CHAR(9)
SET @CODIGO=(SELECT MAX(ID_CLIENTE) AS CODIGO FROM CLIENTE)
SET @CODIGO='MAR'+RIGHT('00000'+LTRIM(RIGHT(ISNULL(@CODIGO,'00000'),6)+1),6)
SELECT @CODIGO AS CODIGO
GO

--EXEC USP_GENERARCODIGOCLIENTE
--GO



-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LISTAR LOS AUTOMOVILES
-- =====================================================================================
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='USP_MARCA_CONSULTA_LISTA' AND TYPE='P')
DROP PROC USP_MARCA_CONSULTA_LISTA
GO

CREATE PROCEDURE USP_MARCA_CONSULTA_LISTA 
AS
SELECT	ID_MARCA,
		NOMBRE
FROM MARCA
WHERE ESTADO = 'A'
GO

EXEC USP_MARCA_CONSULTA_LISTA
GO

-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	23 DE JUNIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA INSERTAR REGISTROS EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_INSERTAR_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_INSERTAR_AUTOMOVIL
GO

CREATE PROCEDURE USP_INSERTAR_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9),
	@ID_MARCA		AS VARCHAR(9),
	@MODELO			AS VARCHAR(9),
	@COLOR			AS VARCHAR(32),
	@PRECIO			AS DECIMAL(15,2),
	@STOCK			AS INT,
	@ESTADO			AS CHAR(1),
	@FECHA_REGISTRO AS VARCHAR(8)
AS
BEGIN
INSERT INTO AUTOMOVIL
	(
	ID_AUTOMOVIL,
	ID_MARCA,
	MODELO,
	COLOR,
	PRECIO,
	STOCK,
	ESTADO,
	FECHA_REGISTRO
	) 
	VALUES	
	(	
	@ID_AUTOMOVIL,
	@ID_MARCA,
	@MODELO,
	@COLOR,
	@PRECIO,
	@STOCK,
	@ESTADO,
	@FECHA_REGISTRO
	)
END
GO


-- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA ACTUALIZAR REGISTROS EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_UPDATE_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_UPDATE_AUTOMOVIL
GO

CREATE PROCEDURE USP_UPDATE_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9),
	@ID_MARCA		AS VARCHAR(9),
	@MODELO			AS VARCHAR(9),
	@COLOR			AS VARCHAR(32),
	@PRECIO			AS DECIMAL(15,2),
	@STOCK			AS INT
AS
UPDATE AUTOMOVIL
   SET	ID_MARCA = @ID_MARCA,
		MODELO = @MODELO,
		COLOR = @COLOR,
		PRECIO = @PRECIO,
		STOCK = @STOCK
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL
GO


-- =================================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA ELIMINAR UN REGISTROS EN lA TABLA AUTOMOVIL - ESTADO INACTIVO
-- =================================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_DELETE_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_DELETE_AUTOMOVIL
GO

CREATE PROCEDURE USP_DELETE_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9)
AS
UPDATE AUTOMOVIL
   SET	ESTADO = 'I'
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL
GO

--EXEC USP_DELETE_AUTOMOVIL 'AUT000001'
--GO


 -- =====================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	01 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA BUSCAR UN REGISTRO EN lA TABLA AUTOMOVIL
-- =====================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_BUSCAR_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_BUSCAR_AUTOMOVIL
GO

CREATE PROCEDURE USP_BUSCAR_AUTOMOVIL
	@ID_AUTOMOVIL	AS VARCHAR(9)
AS
SELECT	ID_AUTOMOVIL,
		ID_MARCA,
		MODELO,
		COLOR,
		PRECIO,
		STOCK,
		ESTADO,
		FECHA_REGISTRO
FROM AUTOMOVIL
WHERE ID_AUTOMOVIL=@ID_AUTOMOVIL AND ESTADO = 'A'
GO

-- =========================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA MOSTRAR LA CANTIDAD DE REGISTROS EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_TOTAL_REGISTROS_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_TOTAL_REGISTROS_AUTOMOVIL
GO

CREATE PROCEDURE USP_TOTAL_REGISTROS_AUTOMOVIL 
AS
SELECT COUNT(*) AS CANTREG
FROM AUTOMOVIL
WHERE ESTADO = 'A'
GO

--EXEC USP_TOTAL_REGISTROS_AUTOMOVIL
--GO

-- =========================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA LA PAGINACIÓN EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_PAGINACION_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_PAGINACION_AUTOMOVIL
GO

CREATE PROCEDURE USP_PAGINACION_AUTOMOVIL
	@NUMPAG	AS INT,
	@FILPAG	AS INT
AS
SELECT * FROM
AUTOMOVIL
WHERE ESTADO = 'A'
ORDER BY ID_AUTOMOVIL ASC
OFFSET @FILPAG*(@NUMPAG-1) ROWS
FETCH NEXT @FILPAG ROWS ONLY;
GO

--EXEC USP_PAGINACION_AUTOMOVIL 3,10
--GO

-- =========================================================================================
-- AUTHOR		:	KATHERINE PAOLA DE LOS SANTOS GARCIA	       
-- CREATE DATE	:	02 DE JULIO DEL 2017
-- DESCRIPTION	:	PROCEDIMIENTO PARA FILTRAR LA CANTIDAD DE REGISTROS EN lA TABLA AUTOMOVIL
-- ===========================================================================================
IF EXISTS(select name from SYSOBJECTS WHERE NAME='USP_FILTRARCANTREG_AUTOMOVIL' AND TYPE='P')
DROP PROC USP_FILTRARCANTREG_AUTOMOVIL
GO

CREATE PROCEDURE USP_FILTRARCANTREG_AUTOMOVIL
	@POSI AS INT
AS
SELECT TOP (@POSI) * FROM AUTOMOVIL 
WHERE ESTADO = 'A'
GO

--EXEC USP_FILTRARCANTREG_AUTOMOVIL 10
--GO


